apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: awsviewer
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - dev
  selector:
    matchLabels:
      app: awsviewer
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
