apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "app.fullname" . | default .Release.Name }}-podmonitor
  labels:
    app.kubernetes.io/name: {{ include "app.name" . | default .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.name" . | default .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  podMetricsEndpoints:
    - port: metrics
      interval: 15s
